### ISSUE TITLE
Implement the GUI for Native Desktop Apps in Tauri 2.0 with raw JavaScript

### ISSUE THREAD

**Issue by ikeen0807** [PatrykHegenberg/caesar-transfer#103]
Summary
Implement the GUI for Native Desktop Apps in Tauri 2.0 with raw JavaScript

Description
This task involves designing and implementing the graphical user interface (GUI) for native desktop applications in the Tauri 2.0 project. The GUI should provide an intuitive and user-friendly interface for users to interact with the application's functionalities.

Acceptance Criteria
Which criteria has to be reached to be accepted

 - [ ] GUI design is consistent with the project's design guidelines
 - [ ]  All required GUI components are implemented and functional
 - [ ] All required GUI components are implemented and functional
 - [ ] GUI is responsive and compatible with various screen sizes and resolutions

Tasks
Which tasks are included to add this feature

 - [ ] Implement GUI components using the chosen framework
 - [ ]  Integrate GUI with backend functionality
 - [ ] Dependencies
 
 Which dependencies are introduced to the project
 - [ ] Integration with existing backend APIs
 - [ ] Compatibility with target platforms (Windows, macOS, Linux)
 
Estimates
Estimated effort for completion: 20 hours

Additional Information
Any additional information relevant to the development.

**Comment by PatrykHegenberg** [comment]
closed, as the decision was made against implementation
